-- NOVA E-COMMERCE
-- Execute este arquivo no SQL Editor do Supabase.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric(10, 2) not null check (price >= 0),
  stock integer not null default 0 check (stock >= 0),
  featured boolean not null default false,
  active boolean not null default true,
  tag text not null default '',
  image text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists products_active_idx on public.products (active);
create index if not exists products_category_idx on public.products (category);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

alter table public.products enable row level security;
alter table public.admin_users enable row level security;

drop policy if exists "Public can view active products" on public.products;
create policy "Public can view active products"
on public.products
for select
to anon, authenticated
using (active = true);

drop policy if exists "Admins can view all products" on public.products;
create policy "Admins can view all products"
on public.products
for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "Admins can create products" on public.products;
create policy "Admins can create products"
on public.products
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "Admins can update products" on public.products;
create policy "Admins can update products"
on public.products
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products"
on public.products
for delete
to authenticated
using ((select public.is_admin()));

drop policy if exists "Users can verify their own admin access" on public.admin_users;
create policy "Users can verify their own admin access"
on public.admin_users
for select
to authenticated
using ((select auth.uid()) = user_id);

grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;
grant usage, select on sequence public.products_id_seq to authenticated;
grant select on public.admin_users to authenticated;

insert into public.products
  (id, name, category, price, stock, featured, active, tag, image)
values
  (1, 'Vaso Cerâmica Areia', 'Casa', 189.90, 12, true, true, 'Feito à mão', 'https://images.unsplash.com/photo-1618220179428-22790b461013?auto=format&fit=crop&w=900&q=85'),
  (2, 'Bolsa Linho Natural', 'Moda', 219.90, 8, true, true, 'Nova coleção', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=85'),
  (3, 'Perfume Âmbar 50 ml', 'Beleza', 259.90, 3, true, true, 'Mais desejado', 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=900&q=85'),
  (4, 'Manta Trama Natural', 'Casa', 149.90, 0, false, true, 'Conforto', 'https://images.unsplash.com/photo-1583845112203-29329902332e?auto=format&fit=crop&w=900&q=85'),
  (5, 'Luminária de Mesa Aura', 'Casa', 329.90, 6, false, true, 'Design autoral', 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=85'),
  (6, 'Carteira Couro Siena', 'Acessórios', 179.90, 9, false, true, 'Essencial', 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=900&q=85'),
  (7, 'Difusor Cedro & Figo', 'Beleza', 119.90, 15, false, true, 'Aroma da casa', 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=900&q=85'),
  (8, 'Relógio Minimal Couro', 'Acessórios', 389.90, 2, false, true, 'Últimas unidades', 'https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&w=900&q=85')
on conflict (id) do nothing;

select setval(
  pg_get_serial_sequence('public.products', 'id'),
  coalesce((select max(id) from public.products), 1),
  (select count(*) > 0 from public.products)
);

-- DEPOIS DE CRIAR O USUÁRIO ADMINISTRADOR EM AUTHENTICATION > USERS,
-- substitua o UUID abaixo e execute apenas esta linha separadamente:
-- insert into public.admin_users (user_id) values ('COLE-AQUI-O-UUID-DO-USUARIO');
