-- NOVA E-COMMERCE V3 - PEDIDOS
-- Execute este arquivo uma única vez no SQL Editor do projeto que já usa a V2.

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique default (
    'NOVA-' ||
    to_char(now(), 'YYYYMMDD') ||
    '-' ||
    upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6))
  ),
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  postal_code text not null,
  address_line text not null,
  address_number text not null,
  complement text not null default '',
  neighborhood text not null,
  city text not null,
  state text not null check (char_length(state) = 2),
  subtotal numeric(10, 2) not null check (subtotal >= 0),
  shipping numeric(10, 2) not null default 0 check (shipping >= 0),
  total numeric(10, 2) not null check (total >= 0),
  payment_method text not null default 'simulated',
  payment_status text not null default 'simulated'
    check (payment_status in ('simulated', 'pending', 'approved', 'refused', 'refunded')),
  status text not null default 'confirmed'
    check (status in ('confirmed', 'preparing', 'shipped', 'delivered', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete restrict,
  product_name text not null,
  unit_price numeric(10, 2) not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  line_total numeric(10, 2) not null check (line_total >= 0),
  created_at timestamptz not null default now()
);

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_status_idx on public.orders (status);
create index if not exists order_items_order_id_idx on public.order_items (order_id);

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

create or replace function public.restore_stock_on_order_cancel()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.status = 'cancelled' and old.status <> 'cancelled' then
    update public.products as product
    set stock = product.stock + item.quantity
    from public.order_items as item
    where item.order_id = new.id
      and item.product_id = product.id;
  elsif old.status = 'cancelled' and new.status <> 'cancelled' then
    raise exception 'Pedidos cancelados não podem ser reativados.';
  end if;

  return new;
end;
$$;

drop trigger if exists orders_restore_stock_on_cancel on public.orders;
create trigger orders_restore_stock_on_cancel
before update of status on public.orders
for each row execute function public.restore_stock_on_order_cancel();

create or replace function public.create_order(
  p_customer jsonb,
  p_items jsonb
)
returns table (
  order_number text,
  subtotal numeric,
  shipping numeric,
  total numeric,
  status text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_item jsonb;
  v_product public.products%rowtype;
  v_quantity integer;
  v_subtotal numeric(10, 2) := 0;
  v_shipping numeric(10, 2) := 0;
  v_total numeric(10, 2) := 0;
  v_order_id bigint;
  v_order_number text;
begin
  if p_customer is null
    or coalesce(btrim(p_customer->>'name'), '') = ''
    or coalesce(btrim(p_customer->>'email'), '') = ''
    or coalesce(btrim(p_customer->>'phone'), '') = ''
    or coalesce(btrim(p_customer->>'postal_code'), '') = ''
    or coalesce(btrim(p_customer->>'address_line'), '') = ''
    or coalesce(btrim(p_customer->>'address_number'), '') = ''
    or coalesce(btrim(p_customer->>'neighborhood'), '') = ''
    or coalesce(btrim(p_customer->>'city'), '') = ''
    or char_length(coalesce(btrim(p_customer->>'state'), '')) <> 2
  then
    raise exception 'Preencha todos os dados obrigatórios do cliente.';
  end if;

  if p_items is null
    or jsonb_typeof(p_items) <> 'array'
    or jsonb_array_length(p_items) = 0
  then
    raise exception 'O carrinho está vazio.';
  end if;

  if jsonb_array_length(p_items) > 30 then
    raise exception 'O pedido ultrapassa o limite de itens.';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(p_items) as entry(item)
    where coalesce(item->>'product_id', '') !~ '^[0-9]+$'
       or coalesce(item->>'quantity', '') !~ '^[1-9][0-9]*$'
  ) then
    raise exception 'O pedido contém itens inválidos.';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(p_items) as entry(item)
    group by item->>'product_id'
    having count(*) > 1
  ) then
    raise exception 'O pedido contém produtos duplicados.';
  end if;

  for v_item in
    select item
    from jsonb_array_elements(p_items) as entry(item)
    order by (item->>'product_id')::bigint
  loop
    v_quantity := (v_item->>'quantity')::integer;

    select *
    into v_product
    from public.products
    where id = (v_item->>'product_id')::bigint
    for update;

    if not found or not v_product.active then
      raise exception 'Um produto do carrinho não está mais disponível.';
    end if;

    if v_product.stock < v_quantity then
      raise exception 'Estoque insuficiente para %.', v_product.name;
    end if;

    v_subtotal := v_subtotal + (v_product.price * v_quantity);
  end loop;

  v_shipping := case when v_subtotal >= 299 then 0 else 24.90 end;
  v_total := v_subtotal + v_shipping;

  insert into public.orders as new_order (
    customer_name,
    customer_email,
    customer_phone,
    postal_code,
    address_line,
    address_number,
    complement,
    neighborhood,
    city,
    state,
    subtotal,
    shipping,
    total
  )
  values (
    btrim(p_customer->>'name'),
    lower(btrim(p_customer->>'email')),
    btrim(p_customer->>'phone'),
    btrim(p_customer->>'postal_code'),
    btrim(p_customer->>'address_line'),
    btrim(p_customer->>'address_number'),
    coalesce(btrim(p_customer->>'complement'), ''),
    btrim(p_customer->>'neighborhood'),
    btrim(p_customer->>'city'),
    upper(btrim(p_customer->>'state')),
    v_subtotal,
    v_shipping,
    v_total
  )
  returning new_order.id, new_order.order_number
  into v_order_id, v_order_number;

  for v_item in
    select item
    from jsonb_array_elements(p_items) as entry(item)
    order by (item->>'product_id')::bigint
  loop
    v_quantity := (v_item->>'quantity')::integer;

    select *
    into v_product
    from public.products
    where id = (v_item->>'product_id')::bigint;

    insert into public.order_items (
      order_id,
      product_id,
      product_name,
      unit_price,
      quantity,
      line_total
    )
    values (
      v_order_id,
      v_product.id,
      v_product.name,
      v_product.price,
      v_quantity,
      v_product.price * v_quantity
    );

    update public.products
    set stock = stock - v_quantity
    where id = v_product.id;
  end loop;

  return query
  select
    v_order_number,
    v_subtotal::numeric,
    v_shipping::numeric,
    v_total::numeric,
    'confirmed'::text;
end;
$$;

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Admins can view orders" on public.orders;
create policy "Admins can view orders"
on public.orders
for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "Admins can update orders" on public.orders;
create policy "Admins can update orders"
on public.orders
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Admins can view order items" on public.order_items;
create policy "Admins can view order items"
on public.order_items
for select
to authenticated
using ((select public.is_admin()));

grant select, update on public.orders to authenticated;
grant select on public.order_items to authenticated;

revoke all on function public.create_order(jsonb, jsonb) from public;
grant execute on function public.create_order(jsonb, jsonb) to anon, authenticated;

