-- ROSINSKI FLORICULTURA V8
-- Execute este arquivo uma única vez no SQL Editor do Supabase após a V7.
-- Adiciona frete por bairro, cupons e armazenamento de imagens do catálogo.

create table if not exists public.delivery_zones (
  id bigint generated by default as identity primary key,
  neighborhood text not null unique,
  fee numeric(10, 2) not null default 0 check (fee >= 0),
  min_order numeric(10, 2) not null default 0 check (min_order >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.coupons (
  id bigint generated by default as identity primary key,
  code text not null unique check (code = upper(code) and length(code) between 3 and 30),
  discount_type text not null check (discount_type in ('percentage', 'fixed')),
  discount_value numeric(10, 2) not null check (discount_value > 0),
  min_order numeric(10, 2) not null default 0 check (min_order >= 0),
  max_discount numeric(10, 2) check (max_discount is null or max_discount > 0),
  starts_at date,
  ends_at date,
  usage_limit integer check (usage_limit is null or usage_limit > 0),
  times_used integer not null default 0 check (times_used >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at is null or starts_at is null or ends_at >= starts_at)
);

alter table public.orders add column if not exists discount numeric(10, 2) not null default 0 check (discount >= 0);
alter table public.orders add column if not exists coupon_code text not null default '';

drop trigger if exists delivery_zones_set_updated_at on public.delivery_zones;
create trigger delivery_zones_set_updated_at
before update on public.delivery_zones
for each row execute function public.set_updated_at();

drop trigger if exists coupons_set_updated_at on public.coupons;
create trigger coupons_set_updated_at
before update on public.coupons
for each row execute function public.set_updated_at();

insert into public.delivery_zones (neighborhood, fee, min_order, active)
values
  ('Centro', 10.00, 0, true),
  ('Brejatuba', 12.90, 0, true),
  ('*', 14.90, 0, true)
on conflict (neighborhood) do nothing;

insert into public.coupons (
  code, discount_type, discount_value, min_order, max_discount,
  starts_at, ends_at, usage_limit, active
)
values ('BEMVINDO10', 'percentage', 10, 100, 50, current_date, current_date + 90, 100, true)
on conflict (code) do nothing;

alter table public.delivery_zones enable row level security;
alter table public.coupons enable row level security;

drop policy if exists "Public can view active delivery zones" on public.delivery_zones;
create policy "Public can view active delivery zones"
on public.delivery_zones for select to anon, authenticated
using (active = true);

drop policy if exists "Admins can view delivery zones" on public.delivery_zones;
create policy "Admins can view delivery zones"
on public.delivery_zones for select to authenticated
using ((select public.is_admin()));

drop policy if exists "Admins can create delivery zones" on public.delivery_zones;
create policy "Admins can create delivery zones"
on public.delivery_zones for insert to authenticated
with check ((select public.is_admin()));

drop policy if exists "Admins can update delivery zones" on public.delivery_zones;
create policy "Admins can update delivery zones"
on public.delivery_zones for update to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Admins can delete delivery zones" on public.delivery_zones;
create policy "Admins can delete delivery zones"
on public.delivery_zones for delete to authenticated
using ((select public.is_admin()));

drop policy if exists "Admins can view coupons" on public.coupons;
create policy "Admins can view coupons"
on public.coupons for select to authenticated
using ((select public.is_admin()));

drop policy if exists "Admins can create coupons" on public.coupons;
create policy "Admins can create coupons"
on public.coupons for insert to authenticated
with check ((select public.is_admin()));

drop policy if exists "Admins can update coupons" on public.coupons;
create policy "Admins can update coupons"
on public.coupons for update to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "Admins can delete coupons" on public.coupons;
create policy "Admins can delete coupons"
on public.coupons for delete to authenticated
using ((select public.is_admin()));

grant select on public.delivery_zones to anon, authenticated;
grant insert, update, delete on public.delivery_zones to authenticated;
grant usage, select on sequence public.delivery_zones_id_seq to authenticated;
grant select, insert, update, delete on public.coupons to authenticated;
grant usage, select on sequence public.coupons_id_seq to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images',
  'product-images',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can view product images" on storage.objects;
create policy "Public can view product images"
on storage.objects for select to anon, authenticated
using (bucket_id = 'product-images');

drop policy if exists "Admins can upload product images" on storage.objects;
create policy "Admins can upload product images"
on storage.objects for insert to authenticated
with check (bucket_id = 'product-images' and (select public.is_admin()));

drop policy if exists "Admins can update product images" on storage.objects;
create policy "Admins can update product images"
on storage.objects for update to authenticated
using (bucket_id = 'product-images' and (select public.is_admin()))
with check (bucket_id = 'product-images' and (select public.is_admin()));

drop policy if exists "Admins can delete product images" on storage.objects;
create policy "Admins can delete product images"
on storage.objects for delete to authenticated
using (bucket_id = 'product-images' and (select public.is_admin()));

create or replace function public.validate_coupon(p_code text, p_subtotal numeric)
returns table (code text, discount numeric)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_coupon public.coupons%rowtype;
  v_discount numeric(10, 2);
begin
  if coalesce(btrim(p_code), '') = '' then
    raise exception 'Digite um cupom.';
  end if;

  select * into v_coupon
  from public.coupons
  where coupons.code = upper(btrim(p_code))
    and coupons.active
  limit 1;

  if not found
    or (v_coupon.starts_at is not null and current_date < v_coupon.starts_at)
    or (v_coupon.ends_at is not null and current_date > v_coupon.ends_at)
    or (v_coupon.usage_limit is not null and v_coupon.times_used >= v_coupon.usage_limit)
  then
    raise exception 'Cupom inválido ou indisponível.';
  end if;

  if p_subtotal < v_coupon.min_order then
    raise exception 'Este cupom exige pedido mínimo de R$ %.', to_char(v_coupon.min_order, 'FM999G999D00');
  end if;

  v_discount := case
    when v_coupon.discount_type = 'percentage' then p_subtotal * (v_coupon.discount_value / 100)
    else v_coupon.discount_value
  end;

  if v_coupon.max_discount is not null then
    v_discount := least(v_discount, v_coupon.max_discount);
  end if;
  v_discount := least(greatest(v_discount, 0), p_subtotal);

  return query select v_coupon.code, round(v_discount, 2);
end;
$$;

revoke all on function public.validate_coupon(text, numeric) from public;
grant execute on function public.validate_coupon(text, numeric) to anon, authenticated;

drop function if exists public.create_order(jsonb, jsonb);
create function public.create_order(
  p_customer jsonb,
  p_items jsonb
)
returns table (
  order_number text,
  subtotal numeric,
  discount numeric,
  shipping numeric,
  total numeric,
  status text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_item jsonb;
  v_product public.products%rowtype;
  v_quantity integer;
  v_subtotal numeric(10, 2) := 0;
  v_discount numeric(10, 2) := 0;
  v_shipping numeric(10, 2) := 0;
  v_total numeric(10, 2) := 0;
  v_order_id bigint;
  v_order_number text;
  v_delivery_method text := coalesce(btrim(p_customer->>'delivery_method'), 'delivery');
  v_delivery_date date;
  v_zone public.delivery_zones%rowtype;
  v_coupon public.coupons%rowtype;
  v_coupon_code text := upper(coalesce(btrim(p_customer->>'coupon_code'), ''));
  v_size_id text;
  v_size jsonb;
  v_addon_ids jsonb;
  v_addon_id text;
  v_addon jsonb;
  v_selected_addons jsonb;
  v_options_total numeric(10, 2);
  v_unit_price numeric(10, 2);
begin
  if p_customer is null
    or coalesce(btrim(p_customer->>'name'), '') = ''
    or coalesce(btrim(p_customer->>'email'), '') = ''
    or coalesce(btrim(p_customer->>'phone'), '') = ''
    or coalesce(btrim(p_customer->>'recipient_name'), '') = ''
    or coalesce(btrim(p_customer->>'recipient_phone'), '') = ''
    or v_delivery_method not in ('delivery', 'pickup')
  then
    raise exception 'Preencha os dados do cliente e do destinatário.';
  end if;

  begin
    v_delivery_date := nullif(btrim(p_customer->>'delivery_date'), '')::date;
  exception when others then
    raise exception 'Informe uma data de entrega válida.';
  end;

  if v_delivery_date is null or v_delivery_date < current_date then
    raise exception 'Escolha uma data de entrega válida.';
  end if;

  if coalesce(btrim(p_customer->>'delivery_period'), '') not in ('morning', 'afternoon', 'evening', 'flexible') then
    raise exception 'Escolha um período de entrega válido.';
  end if;

  if v_delivery_method = 'delivery' and (
    coalesce(btrim(p_customer->>'postal_code'), '') = ''
    or coalesce(btrim(p_customer->>'address_line'), '') = ''
    or coalesce(btrim(p_customer->>'address_number'), '') = ''
    or coalesce(btrim(p_customer->>'neighborhood'), '') = ''
    or lower(coalesce(btrim(p_customer->>'city'), '')) <> 'guaratuba'
    or upper(coalesce(btrim(p_customer->>'state'), '')) <> 'PR'
  ) then
    raise exception 'No momento, as entregas estão disponíveis apenas em Guaratuba/PR.';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'O carrinho está vazio.';
  end if;

  if jsonb_array_length(p_items) > 30 then
    raise exception 'O pedido ultrapassa o limite de itens.';
  end if;

  if exists (
    select 1 from jsonb_array_elements(p_items) as entry(item)
    where coalesce(item->>'product_id', '') !~ '^[0-9]+$'
       or coalesce(item->>'quantity', '') !~ '^[1-9][0-9]*$'
  ) then
    raise exception 'O pedido contém itens inválidos.';
  end if;

  if exists (
    select 1 from jsonb_array_elements(p_items) as entry(item)
    group by item->>'product_id' having count(*) > 1
  ) then
    raise exception 'O pedido contém produtos duplicados.';
  end if;

  for v_item in
    select item from jsonb_array_elements(p_items) as entry(item)
    order by (item->>'product_id')::bigint
  loop
    v_quantity := (v_item->>'quantity')::integer;
    select * into v_product from public.products
    where id = (v_item->>'product_id')::bigint for update;

    if not found or not v_product.active then
      raise exception 'Um produto do carrinho não está mais disponível.';
    end if;
    if v_product.stock < v_quantity then
      raise exception 'Estoque insuficiente para %.', v_product.name;
    end if;

    v_size_id := coalesce(nullif(btrim(v_item->>'size_id'), ''), 'standard');
    select option into v_size
    from jsonb_array_elements(v_product.size_options) as options(option)
    where option->>'id' = v_size_id limit 1;
    if not found then
      raise exception 'O tamanho escolhido para % não está disponível.', v_product.name;
    end if;

    v_addon_ids := coalesce(v_item->'addon_ids', '[]'::jsonb);
    if jsonb_typeof(v_addon_ids) <> 'array' then
      raise exception 'Os complementos escolhidos são inválidos.';
    end if;

    if (select count(*) from jsonb_array_elements_text(v_addon_ids))
       <> (select count(distinct value) from jsonb_array_elements_text(v_addon_ids) as entries(value)) then
      raise exception 'O pedido contém complementos duplicados.';
    end if;

    v_options_total := coalesce((v_size->>'price_delta')::numeric, 0);
    for v_addon_id in select jsonb_array_elements_text(v_addon_ids)
    loop
      select option into v_addon
      from jsonb_array_elements(v_product.addons) as options(option)
      where option->>'id' = v_addon_id limit 1;
      if not found then
        raise exception 'Um complemento escolhido para % não está disponível.', v_product.name;
      end if;
      v_options_total := v_options_total + coalesce((v_addon->>'price')::numeric, 0);
    end loop;

    v_unit_price := v_product.price + v_options_total;
    v_subtotal := v_subtotal + (v_unit_price * v_quantity);
  end loop;

  if v_delivery_method = 'delivery' then
    select * into v_zone from public.delivery_zones
    where active and lower(btrim(neighborhood)) = lower(btrim(p_customer->>'neighborhood'))
    limit 1;
    if not found then
      select * into v_zone from public.delivery_zones where active and neighborhood = '*' limit 1;
    end if;
    if not found then
      raise exception 'A entrega ainda não está configurada para este bairro.';
    end if;
    if v_subtotal < v_zone.min_order then
      raise exception 'Este bairro exige pedido mínimo de R$ %.', to_char(v_zone.min_order, 'FM999G999D00');
    end if;
    v_shipping := v_zone.fee;
  end if;

  if v_coupon_code <> '' then
    select * into v_coupon from public.coupons
    where code = v_coupon_code and active for update;
    if not found
      or (v_coupon.starts_at is not null and current_date < v_coupon.starts_at)
      or (v_coupon.ends_at is not null and current_date > v_coupon.ends_at)
      or (v_coupon.usage_limit is not null and v_coupon.times_used >= v_coupon.usage_limit)
    then
      raise exception 'Cupom inválido ou indisponível.';
    end if;
    if v_subtotal < v_coupon.min_order then
      raise exception 'Este cupom exige pedido mínimo de R$ %.', to_char(v_coupon.min_order, 'FM999G999D00');
    end if;
    v_discount := case
      when v_coupon.discount_type = 'percentage' then v_subtotal * (v_coupon.discount_value / 100)
      else v_coupon.discount_value
    end;
    if v_coupon.max_discount is not null then
      v_discount := least(v_discount, v_coupon.max_discount);
    end if;
    v_discount := round(least(greatest(v_discount, 0), v_subtotal), 2);
  end if;

  v_total := greatest(0, v_subtotal - v_discount) + v_shipping;

  insert into public.orders as new_order (
    customer_name, customer_email, customer_phone,
    postal_code, address_line, address_number, complement, neighborhood, city, state,
    delivery_method, recipient_name, recipient_phone, delivery_date, delivery_period,
    occasion, gift_message, anonymous_delivery, delivery_instructions,
    subtotal, discount, coupon_code, shipping, total, status
  ) values (
    btrim(p_customer->>'name'), lower(btrim(p_customer->>'email')), btrim(p_customer->>'phone'),
    btrim(p_customer->>'postal_code'), btrim(p_customer->>'address_line'), btrim(p_customer->>'address_number'),
    coalesce(btrim(p_customer->>'complement'), ''), btrim(p_customer->>'neighborhood'),
    btrim(p_customer->>'city'), upper(btrim(p_customer->>'state')),
    v_delivery_method, btrim(p_customer->>'recipient_name'), btrim(p_customer->>'recipient_phone'),
    v_delivery_date, btrim(p_customer->>'delivery_period'), coalesce(btrim(p_customer->>'occasion'), ''),
    coalesce(btrim(p_customer->>'gift_message'), ''),
    coalesce((p_customer->>'anonymous_delivery')::boolean, false),
    coalesce(btrim(p_customer->>'delivery_instructions'), ''),
    v_subtotal, v_discount, v_coupon_code, v_shipping, v_total, 'received'
  ) returning new_order.id, new_order.order_number into v_order_id, v_order_number;

  for v_item in
    select item from jsonb_array_elements(p_items) as entry(item)
    order by (item->>'product_id')::bigint
  loop
    v_quantity := (v_item->>'quantity')::integer;
    select * into v_product from public.products where id = (v_item->>'product_id')::bigint;
    v_size_id := coalesce(nullif(btrim(v_item->>'size_id'), ''), 'standard');
    select option into v_size from jsonb_array_elements(v_product.size_options) as options(option)
    where option->>'id' = v_size_id limit 1;
    v_addon_ids := coalesce(v_item->'addon_ids', '[]'::jsonb);
    v_selected_addons := '[]'::jsonb;
    v_options_total := coalesce((v_size->>'price_delta')::numeric, 0);

    for v_addon_id in select jsonb_array_elements_text(v_addon_ids)
    loop
      select option into v_addon from jsonb_array_elements(v_product.addons) as options(option)
      where option->>'id' = v_addon_id limit 1;
      v_options_total := v_options_total + coalesce((v_addon->>'price')::numeric, 0);
      v_selected_addons := v_selected_addons || jsonb_build_array(jsonb_build_object(
        'id', v_addon->>'id', 'label', v_addon->>'label',
        'price', coalesce((v_addon->>'price')::numeric, 0)
      ));
    end loop;

    v_unit_price := v_product.price + v_options_total;
    insert into public.order_items (
      order_id, product_id, product_name, unit_price, quantity, line_total,
      selected_size, selected_addons, options_total
    ) values (
      v_order_id, v_product.id, v_product.name, v_unit_price, v_quantity, v_unit_price * v_quantity,
      coalesce(v_size->>'label', ''), v_selected_addons, v_options_total
    );
    update public.products set stock = stock - v_quantity where id = v_product.id;
  end loop;

  if v_coupon_code <> '' then
    update public.coupons set times_used = times_used + 1 where id = v_coupon.id;
  end if;

  return query select v_order_number, v_subtotal::numeric, v_discount::numeric,
    v_shipping::numeric, v_total::numeric, 'received'::text;
end;
$$;

revoke all on function public.create_order(jsonb, jsonb) from public;
grant execute on function public.create_order(jsonb, jsonb) to anon, authenticated;

drop function if exists public.lookup_order(text, text);
create function public.lookup_order(p_order_number text, p_email text)
returns table (
  order_number text,
  customer_name text,
  status text,
  payment_status text,
  delivery_method text,
  recipient_name text,
  delivery_date date,
  delivery_period text,
  city text,
  subtotal numeric,
  discount numeric,
  coupon_code text,
  shipping numeric,
  total numeric,
  created_at timestamptz,
  items jsonb
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    o.order_number, o.customer_name, o.status, o.payment_status,
    o.delivery_method, o.recipient_name, o.delivery_date, o.delivery_period,
    o.city, o.subtotal, o.discount, o.coupon_code, o.shipping, o.total, o.created_at,
    coalesce((
      select jsonb_agg(jsonb_build_object(
        'product_name', i.product_name, 'quantity', i.quantity,
        'unit_price', i.unit_price, 'line_total', i.line_total,
        'selected_size', i.selected_size, 'selected_addons', i.selected_addons,
        'options_total', i.options_total
      ) order by i.id)
      from public.order_items as i where i.order_id = o.id
    ), '[]'::jsonb) as items
  from public.orders as o
  where upper(o.order_number) = upper(btrim(p_order_number))
    and lower(o.customer_email) = lower(btrim(p_email))
  limit 1;
$$;

revoke all on function public.lookup_order(text, text) from public;
grant execute on function public.lookup_order(text, text) to anon, authenticated;

-- V8.1 · finalização e exclusão segura de produtos

alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders add constraint orders_status_check
  check (status in ('received', 'confirmed', 'preparing', 'shipped', 'delivered', 'completed', 'cancelled'));

create or replace function public.restore_stock_on_order_cancel()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if old.status = 'cancelled' and new.status <> 'cancelled' then
    raise exception 'Pedidos cancelados não podem ser reabertos.';
  elsif old.status = 'completed' and new.status <> 'completed' then
    raise exception 'Pedidos finalizados não podem ser reabertos.';
  elsif new.status = 'cancelled' and old.status <> 'cancelled' then
    update public.products as product
    set stock = product.stock + item.quantity
    from public.order_items as item
    where item.order_id = new.id
      and item.product_id = product.id;
  end if;

  return new;
end;
$$;

alter table public.order_items alter column product_id drop not null;
alter table public.order_items drop constraint if exists order_items_product_id_fkey;
alter table public.order_items add constraint order_items_product_id_fkey
  foreign key (product_id) references public.products(id) on delete set null;

drop policy if exists "Admins can delete products" on public.products;
revoke delete on public.products from authenticated;

create or replace function public.delete_catalog_product(p_product_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'Acesso administrativo necessário.';
  end if;

  if not exists (select 1 from public.products where id = p_product_id) then
    raise exception 'Produto não encontrado.';
  end if;

  if exists (
    select 1
    from public.order_items as item
    join public.orders as order_record on order_record.id = item.order_id
    where item.product_id = p_product_id
      and order_record.status not in ('cancelled', 'completed')
  ) then
    raise exception 'Este produto pertence a um pedido em andamento. Cancele ou finalize o pedido antes de excluí-lo.';
  end if;

  delete from public.products where id = p_product_id;
end;
$$;

revoke all on function public.delete_catalog_product(bigint) from public;
grant execute on function public.delete_catalog_product(bigint) to authenticated;
